name: multilingual-e5-small
model_name: intfloat/multilingual-e5-small
model_revision: main
device: cpu
max_length: 512
batch_size: 32
normalized: true
document_prefix: "passage: "
query_prefix: "query: "
show_progress: true
