"""create initial schema

Revision ID: 909bce321e14
Revises:
Create Date: 2026-08-12 17:53:48.498028
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '909bce321e14'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_versions',
    sa.Column('index_version_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('parser_version', sa.Text(), nullable=False),
    sa.Column('chunking_version', sa.Text(), nullable=False),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('embedding_version', sa.Text(), nullable=True),
    sa.Column('embedding_parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('index_version_id'),
    sa.UniqueConstraint('parser_version', 'chunking_version', 'embedding_model', 'embedding_version', 'embedding_parameters', name='uq_index_versions_identity')
    )
    op.create_table('ingestion_runs',
    sa.Column('run_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('corpus_scope', sa.Text(), nullable=False),
    sa.Column('documents_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('documents_succeeded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('documents_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('documents_skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint('documents_total >= 0'),
    sa.CheckConstraint('documents_succeeded >= 0'),
    sa.CheckConstraint('documents_failed >= 0'),
    sa.CheckConstraint('documents_skipped >= 0'),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed', 'partial')"),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('notes',
    sa.Column('note_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('source_directory', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('language_statistics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('parse_status', sa.Text(), nullable=False),
    sa.Column('anomalies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('source_mtime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parser_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("file_size_bytes >= 0"),
    sa.CheckConstraint("character_count >= 0"),
    sa.CheckConstraint("word_count >= 0"),
    sa.CheckConstraint("parse_status IN ('parsed', 'failed')"),
    sa.PrimaryKeyConstraint('note_id'),
    sa.UniqueConstraint('relative_path')
    )
    op.create_table('chunks',
    sa.Column('chunk_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section_title', sa.Text(), nullable=True),
    sa.Column('section_level', sa.SmallInteger(), nullable=True),
    sa.Column('section_path', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('section_type', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('chunking_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint('chunk_index >= 0'),
    sa.CheckConstraint('section_level BETWEEN 1 AND 6'),
    sa.CheckConstraint('start_offset >= 0'),
    sa.CheckConstraint('end_offset >= 0'),
    sa.CheckConstraint('word_count >= 0'),
    sa.CheckConstraint('token_count >= 0'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], ),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('note_id', 'chunking_version', 'chunk_index', name='uq_chunks_note_version_index')
    )
    op.create_table('ingestion_states',
    sa.Column('state_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('index_version_id', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['index_version_id'], ['index_versions.index_version_id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.run_id'], ),
    sa.PrimaryKeyConstraint('state_id'),
    sa.UniqueConstraint('note_id', 'run_id', name='uq_ingestion_states_note_run'),
    sa.CheckConstraint("status IN ('discovered', 'parsed', 'failed', 'stale')"),
    )
    op.create_table('note_links',
    sa.Column('link_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source_note_id', sa.BigInteger(), nullable=False),
    sa.Column('target_note_id', sa.BigInteger(), nullable=True),
    sa.Column('target_reference', sa.Text(), nullable=False),
    sa.Column('display_text', sa.Text(), nullable=True),
    sa.Column('link_type', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.note_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_note_id'], ['notes.note_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('source_note_id', 'target_reference', 'link_type', name='uq_note_links_source_reference_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_links')
    op.drop_table('ingestion_states')
    op.drop_table('chunks')
    op.drop_table('notes')
    op.drop_table('ingestion_runs')
    op.drop_table('index_versions')
    # ### end Alembic commands ###
